### ISSUE TITLE
Saving the results of auto-discovery.

### ISSUE THREAD

**Issue by majortom64** [nugget/python-insteonplm#39]
It would be nice to be able to save the results of auto-discovery, so that Home Assistant would start faster. It could still do auto-discovery but at least would have all the devices previously discovered.

**Comment by teharris1** [comment]
Agreed. Will put on the roadmap but it should be pretty easy.

**Comment by teharris1** [comment]
This is complete in my latest version.

**Comment by teharris1** [comment]
@majortom64 This should be working in the latest release. You should see a file in your HA config directory called `insteon_plm_device_info.dat`. This file saves the device info (cat, subcat, firmware) so that it does not need to ask the device again at startup. Please confirm we can close this issue.
